services:
  redis:
    image: docker.arvancloud.ir/redis:8.6.0-alpine3.23
    container_name: salonro-redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - salonro

  postgres:
    image: docker.arvancloud.ir/postgres:18.2-alpine3.23
    container_name: salonro-db
    restart: unless-stopped
    ports:
      - "8093:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - salonro-db:/var/lib/postgresql
    networks:
      - salonro

  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${TAG}
    container_name: salonro-laravel
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    volumes:
      - ${BACKEND_PATH}/storage/app/public:/var/www/${PROJECT_NAME}/storage/app/public
      - ./caddy/Caddyfile.production:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - salonro

volumes:
  salonro-db:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local

networks:
  salonro:
    driver: bridge