server {
    listen 80;
    listen [::]:80;
    charset utf-8;

    location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

    location ~ ^/index\.php(/|$) {
        include fastcgi_params;
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_hide_header X-Powered-By;
        fastcgi_param SCRIPT_FILENAME /var/www/salonro/public/index.php;
    }

    location ~ /\.(?!well-known).* {
            deny all;
        }
}
